using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZibStack.NET.TypeGen.Generator;

/// <summary>
/// Emits typed TanStack Query helpers from the endpoint model populated by
/// <see cref="EndpointDiscovery"/>. The output is TypeScript source only:
/// fetch functions, query keys, options factories, React hooks, and cache
/// helpers. DTO/model definitions remain the TypeScript emitter's job.
/// </summary>
internal static class TanStackQueryEmitter
{
    public static IReadOnlyList<EmittedFile> Emit(SchemaModel model, GlobalSettings settings)
    {
        EndpointDiscovery.SynthesizeFromCrudApi(model);
        if (model.Endpoints.Count == 0) return System.Array.Empty<EmittedFile>();

        var query = settings.TanStackQuery;
        var outputDir = ResolveOutputDir(query.OutputDir, settings.TypeScript.OutputDir, model);
        if (!model.TypeScriptNamesResolved)
        {
            TypeScriptNaming.ApplyEmittedNames(model, settings.TypeScript, TypeTarget.TypeScript | TypeTarget.TanStackQuery);
            model.TypeScriptNamesResolved = true;
        }
        var nameLookup = BuildTypeNameLookup(model);

        if (query.FileLayout == QueryFileLayout.SplitByTag)
        {
            var files = new List<EmittedFile>();
            foreach (var group in model.Endpoints
                .GroupBy(e => TagName(e.Tag))
                .OrderBy(g => g.Key, System.StringComparer.Ordinal))
            {
                var fileName = ToKebabCase(group.Key) + ".gen.ts";
                var content = EmitFile(group.ToList(), outputDir, settings, model, nameLookup);
                files.Add(new EmittedFile(TypeTarget.TanStackQuery, outputDir, fileName, content));
            }
            return files;
        }

        return new[]
        {
            new EmittedFile(
                TypeTarget.TanStackQuery,
                outputDir,
                string.IsNullOrWhiteSpace(query.SingleFileName) ? "api.gen.ts" : query.SingleFileName,
                EmitFile(model.Endpoints, outputDir, settings, model, nameLookup))
        };
    }

    private static string EmitFile(
        IReadOnlyList<EndpointInfo> endpoints,
        string queryOutputDir,
        GlobalSettings settings,
        SchemaModel model,
        IReadOnlyDictionary<string, string> nameLookup)
    {
        var query = settings.TanStackQuery;
        var ops = BuildOperations(endpoints, settings, model, nameLookup);
        var sb = new StringBuilder();

        if (query.EmitGeneratedBanner)
            sb.AppendLine("// @generated by ZibStack.NET.TypeGen - do not edit");

        EmitImports(sb, ops, queryOutputDir, settings, model);

        if (string.IsNullOrEmpty(query.ApiClientImportPath))
        {
            EmitDefaultClient(sb, query);
        }

        EmitPaginatedAliases(sb, ops);

        foreach (var group in ops
            .GroupBy(o => o.Tag)
            .OrderBy(g => g.Key, System.StringComparer.Ordinal))
        {
            EmitKeyFactory(sb, group.Key, group.Where(o => o.IsQuery).ToList());
        }

        foreach (var op in ops.OrderBy(o => o.Name, System.StringComparer.Ordinal))
        {
            EmitInputType(sb, op);
            EmitFetchFunction(sb, op, query);
            if (op.IsQuery && query.EmitQueryOptions)
                EmitQueryOptions(sb, op);
            if (!op.IsQuery && query.EmitMutationOptions)
                EmitMutationOptions(sb, op);
            if (query.EmitHooks)
                EmitHook(sb, op, query);
            if (op.IsQuery && query.EmitCacheHelpers && query.EmitQueryOptions)
                EmitPrefetchHelper(sb, op);
        }

        if (query.EmitCacheHelpers)
        {
            foreach (var tag in ops.Select(o => o.Tag).Distinct(System.StringComparer.Ordinal).OrderBy(t => t, System.StringComparer.Ordinal))
                EmitInvalidateHelper(sb, tag);
        }

        return sb.ToString();
    }

    private static List<OperationModel> BuildOperations(
        IReadOnlyList<EndpointInfo> endpoints,
        GlobalSettings settings,
        SchemaModel model,
        IReadOnlyDictionary<string, string> nameLookup)
    {
        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        var operations = new List<OperationModel>();
        var zodNameLookup = BuildZodNameLookup(model);

        foreach (var ep in endpoints.OrderBy(e => e.Tag ?? "", System.StringComparer.Ordinal)
            .ThenBy(e => e.Pattern, System.StringComparer.Ordinal)
            .ThenBy(e => e.Verb, System.StringComparer.Ordinal))
        {
            var tag = TagName(ep.Tag);
            var operationName = MakeUnique(ToCamelIdentifier(ep.OperationId), usedNames);
            var inputTypeName = ToPascalIdentifier(operationName) + "Input";
            var inputMembers = BuildInputMembers(ep, settings, nameLookup, zodNameLookup);
            var response = ResolveResponseType(ep, nameLookup);
            var responseSchema = ResolveResponseSchema(ep, zodNameLookup, settings.Zod.SchemaConstSuffix);

            operations.Add(new OperationModel
            {
                Endpoint = ep,
                Tag = tag,
                Name = operationName,
                InputTypeName = inputTypeName,
                InputMembers = inputMembers,
                ResponseType = response.TypeExpression,
                TypeImports = response.TypeImports,
                PaginatedAliases = response.PaginatedAliases,
                ResponseSchemaExpression = responseSchema.Expression,
                SchemaImports = responseSchema.Imports,
                HasInput = inputMembers.Count > 0,
                HasRequiredInput = inputMembers.Any(m => m.Required),
                IsQuery = string.Equals(ep.Verb, "get", System.StringComparison.OrdinalIgnoreCase),
            });
        }

        return operations;
    }

    private static List<InputMember> BuildInputMembers(
        EndpointInfo ep,
        GlobalSettings settings,
        IReadOnlyDictionary<string, string> nameLookup,
        IReadOnlyDictionary<string, string> zodNameLookup)
    {
        var members = new List<InputMember>();
        var seen = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var p in GetWireParameters(ep, settings))
        {
            if (p.Location == ParamLocation.Body) continue;
            if (!seen.Add(p.Name)) continue;
            var type = ResolveType(p.CSharpType, nameLookup);
            var schema = ResolveZodSchema(p.CSharpType, zodNameLookup, settings.Zod.SchemaConstSuffix);
            members.Add(new InputMember
            {
                WireName = p.Name,
                PropertyName = p.Name,
                TypeExpression = type.TypeExpression,
                Required = p.Required || p.Location == ParamLocation.Route,
                Location = p.Location,
                TypeImports = type.TypeImports,
                PaginatedAliases = type.PaginatedAliases,
                SchemaExpression = schema.Expression,
                SchemaImports = schema.Imports,
            });
        }

        AddMissingRouteInputMembers(ep, members, seen);

        if (ep.RequestBodyCSharpType is not null)
        {
            var body = ResolveType(ep.RequestBodyCSharpType, nameLookup);
            var schema = ResolveZodSchema(ep.RequestBodyCSharpType, zodNameLookup, settings.Zod.SchemaConstSuffix);
            members.Add(new InputMember
            {
                WireName = "body",
                PropertyName = "body",
                TypeExpression = body.TypeExpression,
                Required = true,
                Location = ParamLocation.Body,
                TypeImports = body.TypeImports,
                PaginatedAliases = body.PaginatedAliases,
                SchemaExpression = schema.Expression,
                SchemaImports = schema.Imports,
            });
        }
        else if (ep.RequestBodyArrayItemCSharpType is not null)
        {
            var body = ResolveType(ep.RequestBodyArrayItemCSharpType, nameLookup);
            var schema = ResolveZodSchema(ep.RequestBodyArrayItemCSharpType, zodNameLookup, settings.Zod.SchemaConstSuffix);
            members.Add(new InputMember
            {
                WireName = "body",
                PropertyName = "body",
                TypeExpression = body.TypeExpression + "[]",
                Required = true,
                Location = ParamLocation.Body,
                TypeImports = body.TypeImports,
                PaginatedAliases = body.PaginatedAliases,
                SchemaExpression = schema.Expression is null ? null : $"z.array({schema.Expression})",
                SchemaImports = schema.Imports,
            });
        }

        return members;
    }

    private static void AddMissingRouteInputMembers(EndpointInfo ep, List<InputMember> members, HashSet<string> seen)
    {
        foreach (var routeParam in ExtractRouteTemplateParameters(ep.Pattern))
        {
            if (members.Any(m => m.Location == ParamLocation.Route
                    && string.Equals(m.WireName, routeParam.Name, System.StringComparison.Ordinal)))
                continue;
            if (!seen.Add(routeParam.Name)) continue;

            members.Add(new InputMember
            {
                WireName = routeParam.Name,
                PropertyName = routeParam.Name,
                TypeExpression = routeParam.TypeExpression,
                Required = true,
                Location = ParamLocation.Route,
            });
        }
    }

    private static IEnumerable<EndpointParameter> GetWireParameters(EndpointInfo ep, GlobalSettings settings)
    {
        foreach (var p in ep.Parameters)
            yield return p;

        if (!ep.IsListEndpoint) yield break;

        foreach (var p in ListEndpointParameters(settings.HasQueryDsl))
            yield return p;
    }

    private static IEnumerable<EndpointParameter> ListEndpointParameters(bool hasQueryDsl)
    {
        yield return QueryParam("page", "int");
        yield return QueryParam("pageSize", "int");
        if (!hasQueryDsl) yield break;
        yield return QueryParam("filter", "string");
        yield return QueryParam("sort", "string");
        yield return QueryParam("select", "string");
        yield return QueryParam("count", "bool");
    }

    private static EndpointParameter QueryParam(string name, string type) =>
        new() { Name = name, CSharpType = type, Location = ParamLocation.Query, Required = false };

    private static TypeResolution ResolveResponseType(EndpointInfo ep, IReadOnlyDictionary<string, string> nameLookup)
    {
        if (ep.ResponseCSharpType is not null)
            return ResolveType(ep.ResponseCSharpType, nameLookup);
        if (ep.ResponseArrayItemCSharpType is not null)
        {
            var item = ResolveType(ep.ResponseArrayItemCSharpType, nameLookup);
            item.TypeExpression += "[]";
            return item;
        }
        return new TypeResolution("void");
    }

    private static SchemaResolution ResolveResponseSchema(
        EndpointInfo ep,
        IReadOnlyDictionary<string, string> nameLookup,
        string suffix)
    {
        if (ep.ResponseCSharpType is not null)
            return ResolveZodSchema(ep.ResponseCSharpType, nameLookup, suffix);
        if (ep.ResponseArrayItemCSharpType is not null)
        {
            var item = ResolveZodSchema(ep.ResponseArrayItemCSharpType, nameLookup, suffix);
            if (item.Expression is not null) item.Expression = $"z.array({item.Expression})";
            return item;
        }
        return new SchemaResolution();
    }

    private static SchemaResolution ResolveZodSchema(
        string cSharpType,
        IReadOnlyDictionary<string, string> nameLookup,
        string suffix)
    {
        var nullable = cSharpType.Trim().EndsWith("?", System.StringComparison.Ordinal);
        var t = cSharpType.Trim().TrimEnd('?');
        var result = new SchemaResolution();

        var patch = ExtractGeneric(t, "PatchField");
        if (patch is not null) return ResolveZodSchema(patch, nameLookup, suffix);
        var nullableInner = ExtractGeneric(t, "Nullable", "System.Nullable");
        if (nullableInner is not null)
        {
            var inner = ResolveZodSchema(nullableInner, nameLookup, suffix);
            if (inner.Expression is not null) inner.Expression += ".nullable()";
            return inner;
        }
        var paged = ExtractGeneric(t, "PaginatedResponse");
        if (paged is not null)
        {
            var inner = ResolveZodSchema(paged, nameLookup, suffix);
            if (inner.Expression is not null)
                inner.Expression = $"z.object({{ items: z.array({inner.Expression}), totalCount: z.number().int(), page: z.number().int(), pageSize: z.number().int(), totalPages: z.number().int(), hasNextPage: z.boolean(), hasPreviousPage: z.boolean() }})";
            return inner;
        }
        if (nameLookup.TryGetValue(t, out var mapped))
        {
            result.Expression = mapped + suffix;
            result.Imports.Add(mapped);
        }
        else if (t.EndsWith("[]", System.StringComparison.Ordinal))
        {
            result = ResolveZodSchema(t.Substring(0, t.Length - 2), nameLookup, suffix);
            if (result.Expression is not null) result.Expression = $"z.array({result.Expression})";
        }
        else
        {
            var list = ExtractGeneric(t, "List", "IList", "ICollection", "IEnumerable", "IReadOnlyList", "IReadOnlyCollection", "HashSet", "ISet", "IReadOnlySet");
            if (list is not null)
            {
                result = ResolveZodSchema(list, nameLookup, suffix);
                if (result.Expression is not null) result.Expression = $"z.array({result.Expression})";
            }
            else
            {
                result.Expression = t switch
                {
                    "string" => "z.string()",
                    "bool" or "System.Boolean" => "z.boolean()",
                    "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "System.Int32" or "System.Int64" => "z.number().int()",
                    "float" or "double" or "System.Single" or "System.Double" => "z.number()",
                    "decimal" or "System.Decimal" => "z.string()",
                    "System.Guid" or "Guid" => "z.uuid()",
                    "System.DateTime" or "DateTime" or "System.DateTimeOffset" or "DateTimeOffset" => "z.iso.datetime()",
                    _ => null,
                };
            }
        }

        if (nullable && result.Expression is not null) result.Expression += ".nullable()";
        return result;
    }

    private static Dictionary<string, string> BuildZodNameLookup(SchemaModel model)
    {
        var lookup = new Dictionary<string, string>(System.StringComparer.Ordinal);
        foreach (var c in model.Classes)
            if (!c.TsIgnore)
                lookup[c.CSharpFullName] = c.EmittedName;
        foreach (var e in model.Enums)
            if (!e.TsIgnore)
                lookup[e.CSharpFullName] = e.EmittedName;
        return lookup;
    }

    private static TypeResolution ResolveType(string cSharpType, IReadOnlyDictionary<string, string> nameLookup)
    {
        var t = cSharpType.Trim().TrimEnd('?');
        var result = new TypeResolution("unknown");

        var patchInner = ExtractGeneric(t, "PatchField");
        if (patchInner is not null) return ResolveType(patchInner, nameLookup);

        var nullableInner = ExtractGeneric(t, "Nullable", "System.Nullable");
        if (nullableInner is not null) return ResolveType(nullableInner, nameLookup);

        var pagedInner = ExtractGeneric(t, "PaginatedResponse");
        if (pagedInner is not null)
        {
            var inner = ResolveType(pagedInner, nameLookup);
            var aliasName = "PaginatedResponseOf" + ToPascalIdentifier(RemoveTypeSyntax(inner.TypeExpression));
            result.TypeExpression = aliasName;
            result.TypeImports.UnionWith(inner.TypeImports);
            result.PaginatedAliases[aliasName] = inner.TypeExpression;
            return result;
        }

        if (nameLookup.TryGetValue(t, out var mapped))
            return TypeResolution.WithImport(mapped, mapped);

        if (t.EndsWith("[]", System.StringComparison.Ordinal))
        {
            var inner = ResolveType(t.Substring(0, t.Length - 2), nameLookup);
            inner.TypeExpression += "[]";
            return inner;
        }

        var listInner = ExtractGeneric(t,
            "List", "IList", "ICollection", "IEnumerable", "IReadOnlyList", "IReadOnlyCollection",
            "HashSet", "ISet", "IReadOnlySet",
            "System.Collections.Generic.List", "System.Collections.Generic.IList", "System.Collections.Generic.ICollection",
            "System.Collections.Generic.IEnumerable", "System.Collections.Generic.IReadOnlyList",
            "System.Collections.Generic.IReadOnlyCollection", "System.Collections.Generic.HashSet",
            "System.Collections.Generic.ISet", "System.Collections.Generic.IReadOnlySet");
        if (listInner is not null)
        {
            var inner = ResolveType(listInner, nameLookup);
            inner.TypeExpression += "[]";
            return inner;
        }

        var dict = ExtractTwoGenericArgs(t,
            "Dictionary", "IDictionary", "IReadOnlyDictionary",
            "System.Collections.Generic.Dictionary", "System.Collections.Generic.IDictionary",
            "System.Collections.Generic.IReadOnlyDictionary");
        if (dict is not null)
        {
            var key = ResolveType(dict.Value.K, nameLookup);
            var val = ResolveType(dict.Value.V, nameLookup);
            result.TypeExpression = $"Record<{key.TypeExpression}, {val.TypeExpression}>";
            result.TypeImports.UnionWith(key.TypeImports);
            result.TypeImports.UnionWith(val.TypeImports);
            foreach (var kvp in key.PaginatedAliases) result.PaginatedAliases[kvp.Key] = kvp.Value;
            foreach (var kvp in val.PaginatedAliases) result.PaginatedAliases[kvp.Key] = kvp.Value;
            return result;
        }

        if (TypeScriptNaming.TryMapPrimitive(t, out var primitive)) return new TypeResolution(primitive);

        if (LooksLikeTypeName(t, out var shortName))
            return TypeResolution.WithImport(shortName, shortName);

        return result;
    }

    private static void EmitImports(StringBuilder sb, IReadOnlyList<OperationModel> ops, string queryOutputDir, GlobalSettings settings, SchemaModel model)
    {
        var query = settings.TanStackQuery;
        var queryOps = ops.Where(o => o.IsQuery).ToList();
        var mutationOps = ops.Where(o => !o.IsQuery).ToList();

        var tanstackImports = new List<string>();
        var tanstackTypeImports = new List<string>();
        if (queryOps.Count > 0 && query.EmitQueryOptions) tanstackImports.Add("queryOptions");
        if (mutationOps.Count > 0 && query.EmitMutationOptions) tanstackImports.Add("mutationOptions");
        if (query.EmitHooks)
        {
            if (queryOps.Count > 0) tanstackImports.Add("useQuery");
            if (mutationOps.Count > 0) tanstackImports.Add("useMutation");
            if (mutationOps.Count > 0 && query.EmitCacheHelpers) tanstackImports.Add("useQueryClient");
        }
        if (query.EmitCacheHelpers) tanstackTypeImports.Add("QueryClient");

        if (tanstackImports.Count > 0 || tanstackTypeImports.Count > 0)
        {
            var parts = new List<string>();
            parts.AddRange(tanstackImports.Distinct(System.StringComparer.Ordinal).OrderBy(x => x, System.StringComparer.Ordinal));
            if (tanstackTypeImports.Count > 0)
                parts.AddRange(tanstackTypeImports.Distinct(System.StringComparer.Ordinal).OrderBy(x => x, System.StringComparer.Ordinal).Select(x => "type " + x));
            sb.AppendLine($"import {{ {string.Join(", ", parts)} }} from '@tanstack/react-query';");
        }

        if (!string.IsNullOrEmpty(query.ApiClientImportPath))
            sb.AppendLine($"import {{ {query.ApiClientName} }} from '{query.ApiClientImportPath}';");

        if (query.PayloadValidation != QueryPayloadValidation.None)
        {
            sb.AppendLine("import { z } from 'zod';");
            foreach (var kvp in CollectSchemaImports(ops, queryOutputDir, settings, model).OrderBy(k => k.Key, System.StringComparer.Ordinal))
            {
                var names = string.Join(", ", kvp.Value.OrderBy(n => n, System.StringComparer.Ordinal)
                    .Select(n => n + settings.Zod.SchemaConstSuffix));
                sb.AppendLine($"import {{ {names} }} from '{kvp.Key}';");
            }
        }

        var modelImports = CollectModelImports(ops, queryOutputDir, settings, model);
        foreach (var kvp in modelImports.OrderBy(k => k.Key, System.StringComparer.Ordinal))
        {
            var names = string.Join(", ", kvp.Value.OrderBy(n => n, System.StringComparer.Ordinal));
            sb.AppendLine($"import type {{ {names} }} from '{kvp.Key}';");
        }

        if (tanstackImports.Count > 0 || tanstackTypeImports.Count > 0 || !string.IsNullOrEmpty(query.ApiClientImportPath) || modelImports.Count > 0 || query.PayloadValidation != QueryPayloadValidation.None || query.EmitGeneratedBanner)
            sb.AppendLine();
    }

    private static Dictionary<string, HashSet<string>> CollectSchemaImports(
        IReadOnlyList<OperationModel> ops,
        string queryOutputDir,
        GlobalSettings settings,
        SchemaModel model)
    {
        var names = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var op in ops)
        {
            names.UnionWith(op.SchemaImports);
            if (settings.TanStackQuery.PayloadValidation == QueryPayloadValidation.RequestsAndResponses)
                foreach (var member in op.InputMembers.Where(m => m.Location == ParamLocation.Body))
                    names.UnionWith(member.SchemaImports);
        }
        var result = new Dictionary<string, HashSet<string>>(System.StringComparer.Ordinal);
        if (names.Count == 0) return result;
        if (!string.IsNullOrEmpty(settings.TanStackQuery.SchemasImportPath))
        {
            result[settings.TanStackQuery.SchemasImportPath!] = names;
            return result;
        }
        var zs = settings.Zod;
        var schemaDir = !string.IsNullOrEmpty(zs.OutputDir)
            ? zs.OutputDir!
            : model.Classes.FirstOrDefault()?.OutputDir ?? ".";
        if (zs.FileLayout == ZodFileLayout.SingleFile)
        {
            var file = StripTsExtension(string.IsNullOrWhiteSpace(zs.SingleFileName) ? "schemas.ts" : zs.SingleFileName);
            result[SchemaParser.ComputeRelativeImport(queryOutputDir, schemaDir, file)] = names;
            return result;
        }
        foreach (var name in names)
        {
            var matchingClass = model.Classes.FirstOrDefault(c => c.EmittedName == name);
            var matchingEnum = model.Enums.FirstOrDefault(e => e.EmittedName == name);
            var perTypeDir = matchingClass is not null
                ? matchingClass.HasExplicitOutputDir ? matchingClass.OutputDir : !string.IsNullOrEmpty(zs.OutputDir) ? zs.OutputDir! : matchingClass.OutputDir
                : matchingEnum is not null
                    ? matchingEnum.HasExplicitOutputDir ? matchingEnum.OutputDir : !string.IsNullOrEmpty(zs.OutputDir) ? zs.OutputDir! : matchingEnum.OutputDir
                    : schemaDir;
            var path = SchemaParser.ComputeRelativeImport(queryOutputDir, perTypeDir ?? ".", name + zs.FileSuffix);
            if (!result.TryGetValue(path, out var imported))
                result[path] = imported = new HashSet<string>(System.StringComparer.Ordinal);
            imported.Add(name);
        }
        return result;
    }

    private static Dictionary<string, HashSet<string>> CollectModelImports(
        IReadOnlyList<OperationModel> ops,
        string queryOutputDir,
        GlobalSettings settings,
        SchemaModel model)
    {
        var allTypes = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var op in ops)
        {
            allTypes.UnionWith(op.TypeImports);
            foreach (var member in op.InputMembers)
                allTypes.UnionWith(member.TypeImports);
        }

        foreach (var alias in ops.SelectMany(o => o.PaginatedAliases.Keys))
            allTypes.Remove(alias);

        var byPath = new Dictionary<string, HashSet<string>>(System.StringComparer.Ordinal);
        if (allTypes.Count == 0) return byPath;

        var query = settings.TanStackQuery;
        if (!string.IsNullOrEmpty(query.ModelsImportPath))
        {
            byPath[query.ModelsImportPath!] = allTypes;
            return byPath;
        }

        var ts = settings.TypeScript;
        var modelDir = ResolveModelOutputDir(ts.OutputDir, model);
        if (ts.FileLayout == TypeScriptFileLayout.SingleFile)
        {
            var fileName = StripTsExtension(string.IsNullOrWhiteSpace(ts.SingleFileName) ? "models.ts" : ts.SingleFileName);
            var path = SchemaParser.ComputeRelativeImport(queryOutputDir, modelDir, fileName);
            byPath[path] = allTypes;
            return byPath;
        }

        var dirByTypeName = BuildModelDirLookup(model, ts);
        foreach (var typeName in allTypes)
        {
            var targetDir = dirByTypeName.TryGetValue(typeName, out var perTypeDir) ? perTypeDir : modelDir;
            var path = SchemaParser.ComputeRelativeImport(queryOutputDir, targetDir, typeName);
            if (!byPath.TryGetValue(path, out var names))
                byPath[path] = names = new HashSet<string>(System.StringComparer.Ordinal);
            names.Add(typeName);
        }

        return byPath;
    }

    private static void EmitDefaultClient(StringBuilder sb, TanStackQuerySettings query)
    {
        sb.AppendLine("export type ApiFetchOptions = {");
        sb.AppendLine("    method?: string;");
        sb.AppendLine("    query?: Record<string, unknown>;");
        sb.AppendLine("    headers?: Record<string, string | undefined>;");
        sb.AppendLine("    body?: unknown;");
        sb.AppendLine("    signal?: AbortSignal;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("export class ApiError extends Error {");
        sb.AppendLine("    constructor(public readonly status: number, public readonly body: unknown, message: string) {");
        sb.AppendLine("        super(message);");
        sb.AppendLine("        this.name = 'ApiError';");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"export async function {query.ApiClientName}<T>(path: string, options: ApiFetchOptions = {{}}): Promise<T> {{");
        sb.AppendLine("    const configuredBaseUrl = (() => {");
        sb.AppendLine($"        try {{ return {query.BaseUrlExpression}; }} catch {{ return undefined; }}");
        sb.AppendLine("    })();");
        sb.AppendLine("    const baseUrl = configuredBaseUrl || (typeof window !== 'undefined' ? window.location.origin : 'http://localhost');");
        sb.AppendLine("    const url = new URL(path, baseUrl);");
        sb.AppendLine("    if (options.query) {");
        sb.AppendLine("        for (const [key, value] of Object.entries(options.query)) {");
        sb.AppendLine("            if (value === undefined || value === null) continue;");
        sb.AppendLine("            if (Array.isArray(value)) {");
        sb.AppendLine("                for (const item of value) url.searchParams.append(key, String(item));");
        sb.AppendLine("            } else {");
        sb.AppendLine("                url.searchParams.set(key, String(value));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    const headers: Record<string, string> = {};");
        sb.AppendLine("    if (options.body !== undefined) headers['content-type'] = 'application/json';");
        sb.AppendLine("    if (options.headers) {");
        sb.AppendLine("        for (const [key, value] of Object.entries(options.headers)) {");
        sb.AppendLine("            if (value !== undefined) headers[key] = value;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    const response = await fetch(url.toString(), {");
        sb.AppendLine("        method: options.method ?? 'GET',");
        sb.AppendLine("        headers,");
        sb.AppendLine("        body: options.body === undefined ? undefined : JSON.stringify(options.body),");
        sb.AppendLine("        signal: options.signal,");
        sb.AppendLine("    });");
        sb.AppendLine("    if (!response.ok) {");
        sb.AppendLine("        const errorText = await response.text();");
        sb.AppendLine("        let errorBody: unknown = errorText;");
        sb.AppendLine("        try { errorBody = errorText ? JSON.parse(errorText) : undefined; } catch { }");
        sb.AppendLine("        throw new ApiError(response.status, errorBody, response.statusText || 'Request failed');");
        sb.AppendLine("    }");
        sb.AppendLine("    if (response.status === 204) return undefined as T;");
        sb.AppendLine("    const text = await response.text();");
        sb.AppendLine("    if (!text) return undefined as T;");
        sb.AppendLine("    const contentType = response.headers.get('content-type') ?? '';");
        sb.AppendLine("    return (contentType.includes('application/json') ? JSON.parse(text) : text) as T;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPaginatedAliases(StringBuilder sb, IReadOnlyList<OperationModel> ops)
    {
        var aliases = new Dictionary<string, string>(System.StringComparer.Ordinal);
        foreach (var op in ops)
        {
            foreach (var kvp in op.PaginatedAliases)
                aliases[kvp.Key] = kvp.Value;
            foreach (var member in op.InputMembers)
                foreach (var kvp in member.PaginatedAliases)
                    aliases[kvp.Key] = kvp.Value;
        }

        foreach (var kvp in aliases.OrderBy(k => k.Key, System.StringComparer.Ordinal))
        {
            sb.AppendLine($"export type {kvp.Key} = {{");
            sb.AppendLine($"    items: {kvp.Value}[];");
            sb.AppendLine("    totalCount: number;");
            sb.AppendLine("    page: number;");
            sb.AppendLine("    pageSize: number;");
            sb.AppendLine("    totalPages: number;");
            sb.AppendLine("    hasNextPage: boolean;");
            sb.AppendLine("    hasPreviousPage: boolean;");
            sb.AppendLine("};");
            sb.AppendLine();
        }
    }

    private static void EmitKeyFactory(StringBuilder sb, string tag, IReadOnlyList<OperationModel> queryOps)
    {
        var keyName = KeyFactoryName(tag);
        sb.AppendLine($"export const {keyName} = {{");
        sb.AppendLine($"    all: ['{ToCamelIdentifier(tag)}'] as const,");
        foreach (var op in queryOps.OrderBy(o => o.Name, System.StringComparer.Ordinal))
        {
            if (!op.HasInput)
                sb.AppendLine($"    {op.Name}: () => [...{keyName}.all, '{op.Name}'] as const,");
            else if (op.HasRequiredInput)
                sb.AppendLine($"    {op.Name}: (input: {op.InputTypeName}) => [...{keyName}.all, '{op.Name}', input] as const,");
            else
                sb.AppendLine($"    {op.Name}: (input: {op.InputTypeName} = {{}}) => [...{keyName}.all, '{op.Name}', input] as const,");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    private static void EmitInputType(StringBuilder sb, OperationModel op)
    {
        if (!op.HasInput) return;
        sb.AppendLine($"export type {op.InputTypeName} = {{");
        foreach (var member in op.InputMembers)
        {
            var optional = member.Required ? "" : "?";
            sb.AppendLine($"    {MemberDeclarationName(member.PropertyName)}{optional}: {member.TypeExpression};");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    private static void EmitFetchFunction(StringBuilder sb, OperationModel op, TanStackQuerySettings query)
    {
        sb.Append($"export function {op.Name}(");
        if (op.HasInput)
            sb.Append(op.HasRequiredInput ? $"input: {op.InputTypeName}" : $"input: {op.InputTypeName} = {{}}");
        if (op.HasInput)
            sb.Append(", signal?: AbortSignal");
        else
            sb.Append("signal?: AbortSignal");
        sb.AppendLine($"): Promise<{op.ResponseType}> {{");

        var validateResponse = query.PayloadValidation != QueryPayloadValidation.None
            && op.ResponseSchemaExpression is not null;
        sb.AppendLine($"    return {query.ApiClientName}<{(validateResponse ? "unknown" : op.ResponseType)}>({BuildPathExpression(op)}, {{");
        sb.AppendLine($"        method: '{op.Endpoint.Verb.ToUpperInvariant()}',");
        EmitRequestOptionObject(sb, "query", op.InputMembers.Where(m => m.Location == ParamLocation.Query).ToList());
        EmitRequestOptionObject(sb, "headers", op.InputMembers.Where(m => m.Location == ParamLocation.Header).ToList());
        var body = op.InputMembers.FirstOrDefault(m => m.Location == ParamLocation.Body);
        if (body is not null)
        {
            var bodyExpr = query.PayloadValidation == QueryPayloadValidation.RequestsAndResponses
                && body.SchemaExpression is not null
                ? $"{body.SchemaExpression}.parse({InputAccess(body)})"
                : InputAccess(body);
            sb.AppendLine($"        body: {bodyExpr},");
        }
        sb.AppendLine("        signal,");
        sb.Append("    })");
        if (validateResponse)
            sb.Append($".then(value => {op.ResponseSchemaExpression}.parse(value))");
        sb.AppendLine(";");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitRequestOptionObject(StringBuilder sb, string optionName, IReadOnlyList<InputMember> members)
    {
        if (members.Count == 0) return;
        sb.AppendLine($"        {optionName}: {{");
        foreach (var member in members)
            sb.AppendLine($"            {ObjectKey(member.WireName)}: {InputAccess(member)},");
        sb.AppendLine("        },");
    }

    private static void EmitQueryOptions(StringBuilder sb, OperationModel op)
    {
        sb.Append($"export function {op.Name}Options(");
        if (op.HasInput)
            sb.Append(op.HasRequiredInput ? $"input: {op.InputTypeName}" : $"input: {op.InputTypeName} = {{}}");
        sb.AppendLine(") {");
        var keyCall = BuildKeyCall(op);
        var fetchCall = op.HasInput ? $"{op.Name}(input, signal)" : $"{op.Name}(signal)";
        sb.AppendLine("    return queryOptions({");
        sb.AppendLine($"        queryKey: {keyCall},");
        sb.AppendLine($"        queryFn: ({{ signal }}) => {fetchCall},");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMutationOptions(StringBuilder sb, OperationModel op)
    {
        sb.AppendLine($"export function {op.Name}MutationOptions() {{");
        sb.AppendLine("    return mutationOptions({");
        sb.AppendLine($"        mutationFn: {BuildMutationFn(op)},");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitHook(StringBuilder sb, OperationModel op, TanStackQuerySettings query)
    {
        var hookName = "use" + ToPascalIdentifier(op.Name);
        if (op.IsQuery)
        {
            sb.Append($"export function {hookName}(");
            if (op.HasInput)
                sb.Append(op.HasRequiredInput ? $"input: {op.InputTypeName}" : $"input: {op.InputTypeName} = {{}}");
            sb.AppendLine(") {");
            if (query.EmitQueryOptions)
                sb.AppendLine(op.HasInput
                    ? $"    return useQuery({op.Name}Options(input));"
                    : $"    return useQuery({op.Name}Options());");
            else
            {
                var keyCall = BuildKeyCall(op);
                var fetchCall = op.HasInput ? $"{op.Name}(input, signal)" : $"{op.Name}(signal)";
                sb.AppendLine("    return useQuery({");
                sb.AppendLine($"        queryKey: {keyCall},");
                sb.AppendLine($"        queryFn: ({{ signal }}) => {fetchCall},");
                sb.AppendLine("    });");
            }
            sb.AppendLine("}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"export function {hookName}() {{");
        if (query.EmitCacheHelpers)
        {
            sb.AppendLine("    const queryClient = useQueryClient();");
            sb.AppendLine("    return useMutation({");
            if (query.EmitMutationOptions)
                sb.AppendLine($"        ...{op.Name}MutationOptions(),");
            else
                sb.AppendLine($"        mutationFn: {BuildMutationFn(op)},");
            sb.AppendLine("        onSuccess: async () => {");
            sb.AppendLine($"            await {InvalidateHelperName(op.Tag)}(queryClient);");
            sb.AppendLine("        },");
            sb.AppendLine("    });");
        }
        else if (query.EmitMutationOptions)
        {
            sb.AppendLine($"    return useMutation({op.Name}MutationOptions());");
        }
        else
        {
            sb.AppendLine("    return useMutation({");
            sb.AppendLine($"        mutationFn: {BuildMutationFn(op)},");
            sb.AppendLine("    });");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string BuildMutationFn(OperationModel op) =>
        op.HasInput
            ? $"(input: {op.InputTypeName}) => {op.Name}(input)"
            : $"() => {op.Name}()";

    private static void EmitPrefetchHelper(StringBuilder sb, OperationModel op)
    {
        var name = "prefetch" + ToPascalIdentifier(op.Name);
        sb.Append($"export function {name}(queryClient: QueryClient");
        if (op.HasInput)
            sb.Append(op.HasRequiredInput ? $", input: {op.InputTypeName}" : $", input: {op.InputTypeName} = {{}}");
        sb.AppendLine(") {");
        sb.AppendLine(op.HasInput
            ? $"    return queryClient.prefetchQuery({op.Name}Options(input));"
            : $"    return queryClient.prefetchQuery({op.Name}Options());");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitInvalidateHelper(StringBuilder sb, string tag)
    {
        sb.AppendLine($"export function {InvalidateHelperName(tag)}(queryClient: QueryClient) {{");
        sb.AppendLine($"    return queryClient.invalidateQueries({{ queryKey: {KeyFactoryName(tag)}.all }});");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string BuildPathExpression(OperationModel op)
    {
        var pattern = op.Endpoint.Pattern;
        var sb = new StringBuilder();
        sb.Append('`');
        for (int i = 0; i < pattern.Length; i++)
        {
            var ch = pattern[i];
            if (ch == '`') { sb.Append("\\`"); continue; }
            if (ch == '$') { sb.Append("\\$"); continue; }
            if (ch != '{') { sb.Append(ch); continue; }

            var close = pattern.IndexOf('}', i + 1);
            if (close < 0) { sb.Append(ch); continue; }
            var raw = pattern.Substring(i + 1, close - i - 1);
            var name = CleanRouteParameterName(raw);
            var member = op.InputMembers.FirstOrDefault(m =>
                m.Location == ParamLocation.Route &&
                string.Equals(m.WireName, name, System.StringComparison.Ordinal));
            sb.Append("${encodeURIComponent(String(");
            sb.Append(member is null ? MissingRouteParameterExpression(name) : InputAccess(member));
            sb.Append("))}");
            i = close;
        }
        sb.Append('`');
        return sb.ToString();
    }

    private static string MissingRouteParameterExpression(string name) =>
        "(() => { throw new Error(" + TsString("Missing required route parameter '" + name + "'.") + "); })()";

    private static string BuildKeyCall(OperationModel op)
    {
        var keyName = KeyFactoryName(op.Tag);
        return op.HasInput ? $"{keyName}.{op.Name}(input)" : $"{keyName}.{op.Name}()";
    }

    private static string InputAccess(InputMember member) =>
        IsIdentifier(member.PropertyName) ? "input." + member.PropertyName : $"input[{TsString(member.PropertyName)}]";

    private static string MemberDeclarationName(string name) =>
        IsIdentifier(name) ? name : TsString(name);

    private static string ObjectKey(string name) =>
        IsIdentifier(name) ? name : TsString(name);

    private static Dictionary<string, string> BuildTypeNameLookup(SchemaModel model)
    {
        var lookup = new Dictionary<string, string>(System.StringComparer.Ordinal);
        foreach (var c in model.Classes)
            if (!c.TsIgnore && (c.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) != 0)
                lookup[c.CSharpFullName] = TypeScriptName(c);
        foreach (var e in model.Enums)
            if (!e.TsIgnore && (e.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) != 0)
                lookup[e.CSharpFullName] = TypeScriptName(e);
        return lookup;
    }

    private static string TypeScriptName(SchemaClass cls) =>
        cls.TypeScriptEmittedName ?? cls.EmittedName;

    private static string TypeScriptName(SchemaEnum en) =>
        en.TypeScriptEmittedName ?? en.EmittedName;

    private static string ResolveOutputDir(string? queryDir, string? typeScriptDir, SchemaModel model)
    {
        if (!string.IsNullOrEmpty(queryDir)) return queryDir!;
        if (!string.IsNullOrEmpty(typeScriptDir)) return typeScriptDir!;
        var first = model.Classes.FirstOrDefault(c => (c.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) != 0);
        return first?.OutputDir ?? ".";
    }

    private static string ResolveModelOutputDir(string? typeScriptDir, SchemaModel model)
    {
        if (!string.IsNullOrEmpty(typeScriptDir)) return typeScriptDir!;
        var firstClass = model.Classes.FirstOrDefault(c =>
            !c.TsIgnore && (c.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) != 0);
        if (firstClass is not null) return firstClass.OutputDir;
        var firstEnum = model.Enums.FirstOrDefault(e =>
            !e.TsIgnore && (e.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) != 0);
        return firstEnum?.OutputDir ?? ".";
    }

    private static Dictionary<string, string> BuildModelDirLookup(SchemaModel model, TypeScriptSettings ts)
    {
        var lookup = new Dictionary<string, string>(System.StringComparer.Ordinal);
        foreach (var c in model.Classes)
        {
            if (c.TsIgnore || (c.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) == 0) continue;
            lookup[TypeScriptName(c)] = !string.IsNullOrEmpty(ts.OutputDir) ? ts.OutputDir! : c.OutputDir;
        }
        foreach (var e in model.Enums)
        {
            if (e.TsIgnore || (e.Targets & (TypeTarget.TypeScript | TypeTarget.TanStackQuery)) == 0) continue;
            lookup[TypeScriptName(e)] = !string.IsNullOrEmpty(ts.OutputDir) ? ts.OutputDir! : e.OutputDir;
        }
        return lookup;
    }

    private static string StripTsExtension(string fileName) =>
        fileName.EndsWith(".ts", System.StringComparison.OrdinalIgnoreCase)
            ? fileName.Substring(0, fileName.Length - 3)
            : fileName;

    private static string? ExtractGeneric(string typeName, params string[] names)
    {
        foreach (var n in names)
        {
            var idx = typeName.IndexOf(n + "<", System.StringComparison.Ordinal);
            if (idx < 0) continue;
            if (idx > 0 && (char.IsLetterOrDigit(typeName[idx - 1]) || typeName[idx - 1] == '_')) continue;
            var open = idx + n.Length;
            var inner = ExtractBalanced(typeName, open);
            if (inner != null) return inner;
        }
        return null;
    }

    private static (string K, string V)? ExtractTwoGenericArgs(string typeName, params string[] names)
    {
        var inner = ExtractGeneric(typeName, names);
        if (inner is null) return null;
        int depth = 0;
        for (int i = 0; i < inner.Length; i++)
        {
            if (inner[i] == '<') depth++;
            else if (inner[i] == '>') depth--;
            else if (inner[i] == ',' && depth == 0)
                return (inner.Substring(0, i).Trim(), inner.Substring(i + 1).Trim());
        }
        return null;
    }

    private static string? ExtractBalanced(string s, int openAngleBracketIndex)
    {
        if (openAngleBracketIndex >= s.Length || s[openAngleBracketIndex] != '<') return null;
        int depth = 1;
        for (int i = openAngleBracketIndex + 1; i < s.Length; i++)
        {
            if (s[i] == '<') depth++;
            else if (s[i] == '>')
            {
                depth--;
                if (depth == 0) return s.Substring(openAngleBracketIndex + 1, i - openAngleBracketIndex - 1);
            }
        }
        return null;
    }

    private static string CleanRouteParameterName(string raw)
    {
        var s = raw.Trim();
        while (s.StartsWith("*", System.StringComparison.Ordinal)) s = s.Substring(1);
        var colon = s.IndexOf(':');
        if (colon >= 0) s = s.Substring(0, colon);
        var equals = s.IndexOf('=');
        if (equals >= 0) s = s.Substring(0, equals);
        var optional = s.IndexOf('?');
        if (optional >= 0) s = s.Substring(0, optional);
        return s.Trim();
    }

    private static IEnumerable<(string Name, string TypeExpression)> ExtractRouteTemplateParameters(string pattern)
    {
        for (var i = 0; i < pattern.Length; i++)
        {
            if (pattern[i] != '{') continue;
            var close = pattern.IndexOf('}', i + 1);
            if (close < 0) yield break;

            var raw = pattern.Substring(i + 1, close - i - 1);
            var name = CleanRouteParameterName(raw);
            if (name.Length > 0)
                yield return (name, InferRouteTypeExpression(raw));
            i = close;
        }
    }

    private static string InferRouteTypeExpression(string raw)
    {
        var colon = raw.IndexOf(':');
        if (colon < 0 || colon + 1 >= raw.Length) return "string";

        var constraintStart = colon + 1;
        var constraintEnd = FirstNonNegative(
            raw.IndexOf(':', constraintStart),
            raw.IndexOf('=', constraintStart),
            raw.IndexOf('?', constraintStart));
        var constraint = constraintEnd >= 0
            ? raw.Substring(constraintStart, constraintEnd - constraintStart)
            : raw.Substring(constraintStart);

        var csharpType = constraint.Trim().ToLowerInvariant() switch
        {
            "bool" or "boolean" => "bool",
            "datetime" => "System.DateTime",
            "decimal" => "decimal",
            "double" => "double",
            "float" => "float",
            "guid" => "System.Guid",
            "int" => "int",
            "long" => "long",
            "short" => "short",
            _ => "string",
        };

        return TypeScriptNaming.TryMapPrimitive(csharpType, out var primitive) ? primitive : "string";
    }

    private static int FirstNonNegative(params int[] values)
    {
        var best = -1;
        foreach (var value in values)
        {
            if (value < 0) continue;
            if (best < 0 || value < best) best = value;
        }
        return best;
    }

    private static bool LooksLikeTypeName(string name, out string shortName)
    {
        shortName = name;
        if (string.IsNullOrEmpty(name)) return false;
        if (name.IndexOf('<') >= 0) return false;
        var dot = name.LastIndexOf('.');
        if (dot >= 0) shortName = name.Substring(dot + 1);
        if (shortName.Length == 0 || !char.IsUpper(shortName[0])) return false;
        foreach (var ch in shortName)
            if (!char.IsLetterOrDigit(ch) && ch != '_') return false;
        return true;
    }

    private static string TagName(string? tag) =>
        string.IsNullOrWhiteSpace(tag) ? "Api" : ToPascalIdentifier(tag!);

    private static string KeyFactoryName(string tag) => ToCamelIdentifier(tag) + "Keys";

    private static string InvalidateHelperName(string tag) => "invalidate" + ToPascalIdentifier(tag) + "Queries";

    private static string MakeUnique(string name, HashSet<string> used)
    {
        var baseName = string.IsNullOrEmpty(name) ? "operation" : name;
        var candidate = baseName;
        var index = 2;
        while (!used.Add(candidate))
            candidate = baseName + index++;
        return candidate;
    }

    private static string ToCamelIdentifier(string value)
    {
        var pascal = ToPascalIdentifier(value);
        return string.IsNullOrEmpty(pascal) ? "operation" : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
    }

    private static string ToPascalIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "Operation";
        var sb = new StringBuilder();
        var upperNext = true;
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                if (sb.Length == 0 && char.IsDigit(ch)) sb.Append('_');
                sb.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
                upperNext = false;
            }
            else
            {
                upperNext = true;
            }
        }
        return sb.Length == 0 ? "Operation" : sb.ToString();
    }

    private static string ToKebabCase(string name)
    {
        var separated = ToSeparated(name, '-');
        return string.IsNullOrEmpty(separated) ? "api" : separated;
    }

    private static string ToSeparated(string name, char sep)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            var ch = name[i];
            if (!char.IsLetterOrDigit(ch))
            {
                if (sb.Length > 0 && sb[sb.Length - 1] != sep) sb.Append(sep);
                continue;
            }
            if (i > 0 && char.IsUpper(ch) && sb.Length > 0 && sb[sb.Length - 1] != sep)
                sb.Append(sep);
            sb.Append(char.ToLowerInvariant(ch));
        }
        return sb.ToString().Trim(sep);
    }

    private static string RemoveTypeSyntax(string typeExpression)
    {
        var sb = new StringBuilder();
        foreach (var ch in typeExpression)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_') sb.Append(ch);
        }
        return sb.Length == 0 ? "Value" : sb.ToString();
    }

    private static bool IsIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value)) return false;
        if (!(char.IsLetter(value[0]) || value[0] == '_' || value[0] == '$')) return false;
        for (int i = 1; i < value.Length; i++)
        {
            var ch = value[i];
            if (!(char.IsLetterOrDigit(ch) || ch == '_' || ch == '$')) return false;
        }
        return true;
    }

    private static string TsString(string value) =>
        "'" + value.Replace("\\", "\\\\").Replace("'", "\\'") + "'";

    private sealed class OperationModel
    {
        public EndpointInfo Endpoint { get; set; } = new();
        public string Tag { get; set; } = "";
        public string Name { get; set; } = "";
        public string InputTypeName { get; set; } = "";
        public List<InputMember> InputMembers { get; set; } = new();
        public string ResponseType { get; set; } = "void";
        public HashSet<string> TypeImports { get; set; } = new(System.StringComparer.Ordinal);
        public Dictionary<string, string> PaginatedAliases { get; set; } = new(System.StringComparer.Ordinal);
        public string? ResponseSchemaExpression { get; set; }
        public HashSet<string> SchemaImports { get; set; } = new(System.StringComparer.Ordinal);
        public bool HasInput { get; set; }
        public bool HasRequiredInput { get; set; }
        public bool IsQuery { get; set; }
    }

    private sealed class InputMember
    {
        public string WireName { get; set; } = "";
        public string PropertyName { get; set; } = "";
        public string TypeExpression { get; set; } = "unknown";
        public bool Required { get; set; }
        public ParamLocation Location { get; set; }
        public HashSet<string> TypeImports { get; set; } = new(System.StringComparer.Ordinal);
        public Dictionary<string, string> PaginatedAliases { get; set; } = new(System.StringComparer.Ordinal);
        public string? SchemaExpression { get; set; }
        public HashSet<string> SchemaImports { get; set; } = new(System.StringComparer.Ordinal);
    }

    private sealed class SchemaResolution
    {
        public string? Expression { get; set; }
        public HashSet<string> Imports { get; set; } = new(System.StringComparer.Ordinal);
    }

    private sealed class TypeResolution
    {
        public TypeResolution(string typeExpression)
        {
            TypeExpression = typeExpression;
        }

        public string TypeExpression { get; set; }
        public HashSet<string> TypeImports { get; } = new(System.StringComparer.Ordinal);
        public Dictionary<string, string> PaginatedAliases { get; } = new(System.StringComparer.Ordinal);

        public static TypeResolution WithImport(string typeExpression, string importName)
        {
            var resolution = new TypeResolution(typeExpression);
            resolution.TypeImports.Add(importName);
            return resolution;
        }
    }
}
