namespace ZibStack.NET.Validation;

public sealed partial class ValidationGenerator
{
    private const string ZValidateAttributeFqn = "ZibStack.NET.Validation.ZValidateAttribute";

    private const string ZValidateAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Generates a compile-time <see cref=""IValidatable.Validate""/> method from validation
    /// attributes (<see cref=""ZRequiredAttribute""/>, <see cref=""ZRangeAttribute""/>, etc.)
    /// and optional fluent rules via <see cref=""IValidationConfigurator{T}""/>.
    /// <para>No reflection, no runtime overhead — validation code is emitted by the source generator.</para>
    /// <para>Supports nested object/collection validation and cross-field rules.</para>
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class ZValidateAttribute : System.Attribute { }
}
";

    private const string ValidationResultSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>A single validation error with property path and message.</summary>
    public sealed class ValidationError
    {
        /// <summary>Dot-separated property path (e.g. ""BillingAddress.Street"", ""Notes[1].Text""). Empty for class-level rules.</summary>
        public string Property { get; }

        /// <summary>Error message (e.g. ""is required."").</summary>
        public string Message { get; }

        /// <summary>Full error string: Property + Message (e.g. ""BillingAddress.Street is required."").</summary>
        public string FullMessage => string.IsNullOrEmpty(Property) ? Message : Property + "": "" + Message;

        public ValidationError(string property, string message)
        {
            Property = property;
            Message = message;
        }

        public override string ToString() => FullMessage;
    }

    /// <summary>Result of a validation operation.</summary>
    public sealed class ValidationResult
    {
        public static readonly ValidationResult Success = new(
            System.Array.Empty<ValidationError>());

        /// <summary>Structured errors with property path and message.</summary>
        public System.Collections.Generic.IReadOnlyList<ValidationError> ValidationErrors { get; }

        /// <summary>Flat error messages for backward compatibility.</summary>
        public System.Collections.Generic.IReadOnlyList<string> Errors { get; }

        public bool IsValid => ValidationErrors.Count == 0;

        public ValidationResult(System.Collections.Generic.IReadOnlyList<ValidationError> errors)
        {
            ValidationErrors = errors;
            var flat = new string[errors.Count];
            for (int i = 0; i < errors.Count; i++) flat[i] = errors[i].FullMessage;
            Errors = flat;
        }

        /// <summary>Backward-compatible constructor from flat string list.</summary>
        public ValidationResult(System.Collections.Generic.IReadOnlyList<string> errors)
        {
            var structured = new ValidationError[errors.Count];
            for (int i = 0; i < errors.Count; i++) structured[i] = new ValidationError("""", errors[i]);
            ValidationErrors = structured;
            Errors = errors;
        }

        /// <summary>Errors grouped by property path — matches ASP.NET ModelState shape.</summary>
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> ToDictionary()
        {
            var dict = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>>();
            foreach (var e in ValidationErrors)
            {
                var key = string.IsNullOrEmpty(e.Property) ? """" : e.Property;
                if (!dict.TryGetValue(key, out var list))
                {
                    list = new System.Collections.Generic.List<string>();
                    dict[key] = list;
                }
                list.Add(e.Message);
            }
            return dict;
        }
    }

    /// <summary>Interface implemented by all [ZValidate]-decorated types.</summary>
    public interface IValidatable
    {
        ValidationResult Validate(ValidationContext? context = null);
    }

    /// <summary>
    /// Runtime context passed through the validation chain. Carries DI service provider,
    /// parent reference, property path, root object, and a user-data bag.
    /// </summary>
    public sealed class ValidationContext
    {
        /// <summary>
        /// DI service provider for resolving services like <see cref=""IValidationLocalizer""/>.
        /// Auto-populated by <see cref=""ValidationServiceProvider.ConfigureValidation""/>.
        /// </summary>
        public System.IServiceProvider? ServiceProvider { get; set; }

        /// <summary>The object that triggered this nested validation.</summary>
        public object? Parent { get; set; }

        /// <summary>Dot-separated path from root (e.g. ""Order.Address.City"").</summary>
        public string Path { get; set; } = """";

        /// <summary>The top-level object that started the validation chain.</summary>
        public object? RootObject { get; set; }

        /// <summary>User-defined key-value bag for custom data.</summary>
        public System.Collections.Generic.Dictionary<string, object?> Items { get; } = new();

        /// <summary>Resolve a service from DI. Returns null if not registered or no provider.</summary>
        public T? GetService<T>() where T : class
            => ServiceProvider?.GetService(typeof(T)) as T;

        internal ValidationContext ForNested(object parent, string propertyName)
        {
            var ctx = new ValidationContext
            {
                ServiceProvider = ServiceProvider,
                Parent = parent,
                Path = string.IsNullOrEmpty(Path) ? propertyName : Path + ""."" + propertyName,
                RootObject = RootObject ?? parent,
            };
            foreach (var kv in Items) ctx.Items[kv.Key] = kv.Value;
            return ctx;
        }
    }

    /// <summary>
    /// Implement to provide localized validation error messages.
    /// Register in DI: <c>builder.Services.AddSingleton&lt;IValidationLocalizer, MyLocalizer&gt;();</c>
    /// </summary>
    public interface IValidationLocalizer
    {
        /// <summary>
        /// Return a localized message for the given property and default message.
        /// Return null to use the default (English) message.
        /// </summary>
        string? GetMessage(string property, string defaultMessage);
    }

    /// <summary>
    /// Static bridge between DI and the validation runtime. Call
    /// <c>app.Services.ConfigureValidation();</c> once at startup.
    /// </summary>
    public static class ValidationServiceProvider
    {
        /// <summary>The application's service provider. Set by <see cref=""ConfigureValidation""/>.</summary>
        public static System.IServiceProvider? ServiceProvider { get; set; }

        /// <summary>
        /// Bridges DI into the validation runtime. Call once at startup:
        /// <code>app.Services.ConfigureValidation();</code>
        /// </summary>
        public static System.IServiceProvider ConfigureValidation(this System.IServiceProvider services)
        {
            ServiceProvider = services ?? throw new System.ArgumentNullException(nameof(services));
            return services;
        }
    }
}
";

    // Attribute sources for custom rules
    private const string ZRequiredAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Property must not be null (or empty/whitespace for strings).
    /// Fluent equivalent: <c>b.Property(x => x.Prop).Required()</c> via <see cref=""IValidationConfigurator{T}""/>.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRequiredAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZMinLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at least this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMinLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMinLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZMaxLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at most this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMaxLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMaxLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZRangeAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Numeric value must be within the specified range (inclusive).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRangeAttribute : System.Attribute
    {
        public double Min { get; }
        public double Max { get; }
        public string? Message { get; set; }
        public ZRangeAttribute(double min, double max) { Min = min; Max = max; }
    }
}
";

    private const string ZEmailAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid email address.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZEmailAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZUrlAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid URL.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZUrlAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string RegexAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must match the specified regex pattern.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMatchAttribute : System.Attribute
    {
        public string Pattern { get; }
        public string? Message { get; set; }
        public ZMatchAttribute(string pattern) => Pattern = pattern;
    }
}
";

    private const string ZNotEmptyAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Collection must contain at least one element. String must not be empty or whitespace.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZNotEmptyAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZInAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Value must be one of the specified values.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZInAttribute : System.Attribute
    {
        public string[] Values { get; }
        public string? Message { get; set; }
        public ZInAttribute(params string[] values) => Values = values;
    }
}
";

    private const string ZNotInAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Value must NOT be one of the specified values.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZNotInAttribute : System.Attribute
    {
        public string[] Values { get; }
        public string? Message { get; set; }
        public ZNotInAttribute(params string[] values) => Values = values;
    }
}
";

    private const string ZCreditCardAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid credit card number (Luhn algorithm).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZCreditCardAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZIbanAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid IBAN (ISO 13616 mod-97 check).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZIbanAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZPhoneAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid phone number.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZPhoneAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZCascadeAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// When applied to a property with multiple validation rules, stops after the first failure
    /// (remaining rules for that property are skipped).
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property)]
    internal sealed class ZCascadeAttribute : System.Attribute { }
}
";

    private const string CrossFieldInterfacesSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Implement on a <c>[ZValidate]</c> class to define validation rules via fluent DSL.
    /// The generator parses <see cref=""Configure""/> at compile time — it is never invoked at runtime.
    /// <code>
    /// [ZValidate]
    /// public partial class MyForm : IValidationConfigurator&lt;MyForm&gt;
    /// {
    ///     public string Email { get; set; } = """";
    ///     public DateTime Start { get; set; }
    ///     public DateTime End { get; set; }
    ///
    ///     public void Configure(IValidationBuilder&lt;MyForm&gt; b)
    ///     {
    ///         b.Property(x => x.Email).Required().Email();
    ///         b.Rule(x => x.End > x.Start, ""End must be after Start"");
    ///     }
    /// }
    /// </code>
    /// </summary>
    public interface IValidationConfigurator<T>
    {
        /// <summary>Define validation rules for <typeparamref name=""T""/>. Parsed at compile time.</summary>
        void Configure(IValidationBuilder<T> b);
    }

    /// <summary>
    /// Fluent builder for validation rules. Supports per-property rules and cross-field expressions.
    /// </summary>
    public interface IValidationBuilder<T>
    {
        /// <summary>
        /// Add a cross-field rule with a predicate. Any valid C# expression or statement body works.
        /// The predicate is parsed at compile time by the source generator — it is never executed.
        /// <code>b.Rule(x => x.EndDate > x.StartDate, ""EndDate must be after StartDate"");</code>
        /// <code>b.Rule(x => { var total = x.Items.Sum(i => i.Price); return total > 0; }, ""msg"");</code>
        /// </summary>
        IValidationBuilder<T> Rule(System.Func<T, bool> predicate, string message);

        /// <summary>
        /// Begin a per-property rule chain. Supports both single-property rules and cross-field comparisons.
        /// <code>b.Property(x => x.Email).Required().Email();</code>
        /// </summary>
        IPropertyValidationBuilder<T> Property(System.Func<T, object?> selector);

        /// <summary>
        /// Conditional validation block. Rules inside are only applied when the condition is true.
        /// <code>b.When(x => x.RequiresShipping, then => { then.Rule(...); });</code>
        /// </summary>
        IValidationBuilder<T> When(System.Func<T, bool> condition, System.Action<IValidationBuilder<T>> then);

        /// <summary>
        /// Inverse conditional. Rules inside are only applied when the condition is FALSE.
        /// <code>b.Unless(x => x.IsAdmin, then => { then.Rule(...); });</code>
        /// </summary>
        IValidationBuilder<T> Unless(System.Func<T, bool> condition, System.Action<IValidationBuilder<T>> then);

        /// <summary>
        /// Named rule set. Rules inside are only executed when the set is explicitly requested
        /// (or when no sets are specified — all sets run by default).
        /// <code>b.RuleSet(""Create"", set => { set.Rule(...); });</code>
        /// </summary>
        IValidationBuilder<T> RuleSet(string name, System.Action<IValidationBuilder<T>> rules);
    }

    /// <summary>
    /// Per-property validation builder. Chain rules fluently — each returns the builder for further chaining.
    /// </summary>
    public interface IPropertyValidationBuilder<T>
    {
        // ── Single-property rules (equivalent to [Z*] attributes) ───────

        /// <summary>Property must not be null (or empty/whitespace for strings). Equivalent to <c>[ZRequired]</c>.</summary>
        IPropertyValidationBuilder<T> Required(string? message = null);

        /// <summary>String/collection must have at least <paramref name=""length""/> characters/items. Equivalent to <c>[ZMinLength]</c>.</summary>
        IPropertyValidationBuilder<T> MinLength(int length, string? message = null);

        /// <summary>String/collection must have at most <paramref name=""length""/> characters/items. Equivalent to <c>[ZMaxLength]</c>.</summary>
        IPropertyValidationBuilder<T> MaxLength(int length, string? message = null);

        /// <summary>Numeric value must be within range (inclusive). Equivalent to <c>[ZRange]</c>.</summary>
        IPropertyValidationBuilder<T> Range(double min, double max, string? message = null);

        /// <summary>Must be a valid email address. Equivalent to <c>[ZEmail]</c>.</summary>
        IPropertyValidationBuilder<T> Email(string? message = null);

        /// <summary>Must be a valid absolute URL. Equivalent to <c>[ZUrl]</c>.</summary>
        IPropertyValidationBuilder<T> Url(string? message = null);

        /// <summary>Must match the regex <paramref name=""pattern""/>. Equivalent to <c>[ZMatch]</c>.</summary>
        IPropertyValidationBuilder<T> Match(string pattern, string? message = null);

        /// <summary>Collection must have items; string must not be whitespace. Equivalent to <c>[ZNotEmpty]</c>.</summary>
        IPropertyValidationBuilder<T> NotEmpty(string? message = null);

        /// <summary>Value must be one of the specified allowed values. Equivalent to <c>[ZIn]</c>.</summary>
        IPropertyValidationBuilder<T> In(params string[] values);

        /// <summary>Value must NOT be one of the specified values. Equivalent to <c>[ZNotIn]</c>.</summary>
        IPropertyValidationBuilder<T> NotIn(params string[] values);

        /// <summary>Must pass Luhn algorithm (credit card number). Equivalent to <c>[ZCreditCard]</c>.</summary>
        IPropertyValidationBuilder<T> CreditCard(string? message = null);

        /// <summary>Must be a valid IBAN. Equivalent to <c>[ZIban]</c>.</summary>
        IPropertyValidationBuilder<T> Iban(string? message = null);

        /// <summary>Must be a valid phone number format. Equivalent to <c>[ZPhone]</c>.</summary>
        IPropertyValidationBuilder<T> Phone(string? message = null);

        // ── Cross-field comparisons ─────────────────────────────────────

        /// <summary>This property must be greater than <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> GreaterThan(System.Func<T, object?> other, string? message = null);

        /// <summary>This property must be greater than or equal to <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> GreaterThanOrEqual(System.Func<T, object?> other, string? message = null);

        /// <summary>This property must be less than <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> LessThan(System.Func<T, object?> other, string? message = null);

        /// <summary>This property must be less than or equal to <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> LessThanOrEqual(System.Func<T, object?> other, string? message = null);

        /// <summary>This property must equal <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> EqualTo(System.Func<T, object?> other, string? message = null);

        /// <summary>This property must not equal <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> NotEqualTo(System.Func<T, object?> other, string? message = null);

        /// <summary>Start a new property chain.</summary>
        IPropertyValidationBuilder<T> Property(System.Func<T, object?> selector);
    }
}
";

    private const string ValidationEndpointFilterSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// ASP.NET Core Minimal API endpoint filter that auto-validates <see cref=""IValidatable""/> parameters.
    /// <para>Usage:</para>
    /// <code>
    /// app.MapPost(""/api/users"", (CreateUserRequest req) => ...)
    ///    .WithValidation();
    /// </code>
    /// </summary>
    public static class ValidationEndpointFilterExtensions
    {
        /// <summary>
        /// Adds automatic validation to a minimal API endpoint. Any parameter implementing
        /// <see cref=""IValidatable""/> is validated before the handler runs. Returns 400
        /// with structured errors if validation fails.
        /// </summary>
        public static Microsoft.AspNetCore.Builder.RouteHandlerBuilder WithValidation(
            this Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            return builder.AddEndpointFilter(async (context, next) =>
            {
                var ctx = new ValidationContext { ServiceProvider = ValidationServiceProvider.ServiceProvider };
                foreach (var arg in context.Arguments)
                {
                    if (arg is IValidatable validatable)
                    {
                        var result = validatable.Validate(ctx);
                        if (!result.IsValid)
                        {
                            return Microsoft.AspNetCore.Http.Results.ValidationProblem(
                                result.ToDictionary()
                                    .ToDictionary(
                                        kv => kv.Key,
                                        kv => kv.Value.ToArray() as string[]));
                        }
                    }
                }
                return await next(context);
            });
        }

        /// <summary>
        /// Adds automatic validation to ALL endpoints in this group.
        /// </summary>
        public static Microsoft.AspNetCore.Routing.RouteGroupBuilder WithValidation(
            this Microsoft.AspNetCore.Routing.RouteGroupBuilder group)
        {
            group.AddEndpointFilter(async (context, next) =>
            {
                var ctx = new ValidationContext { ServiceProvider = ValidationServiceProvider.ServiceProvider };
                foreach (var arg in context.Arguments)
                {
                    if (arg is IValidatable validatable)
                    {
                        var result = validatable.Validate(ctx);
                        if (!result.IsValid)
                        {
                            return Microsoft.AspNetCore.Http.Results.ValidationProblem(
                                result.ToDictionary()
                                    .ToDictionary(
                                        kv => kv.Key,
                                        kv => kv.Value.ToArray() as string[]));
                        }
                    }
                }
                return await next(context);
            });
            return group;
        }
    }
}
";
}
