using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZibStack.NET.Validation;

public sealed partial class ValidationGenerator
{
    private static string GenerateValidation(ValidationInfo info)
    {
        _blockRuleCounter = 0;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Validation for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Validation;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName} : IValidatable");
        sb.AppendLine("{");

        bool hasRuleSets = info.RuleSetRules.Count > 0;

        if (hasRuleSets)
        {
            sb.AppendLine("    public ValidationResult Validate(ValidationContext? context = null) => Validate(context, null);");
            sb.AppendLine();
            sb.AppendLine("    public ValidationResult Validate(ValidationContext? context, params string[]? ruleSets)");
        }
        else
        {
            sb.AppendLine("    public ValidationResult Validate(ValidationContext? context = null)");
        }

        sb.AppendLine("    {");
        sb.AppendLine("        context ??= new ValidationContext { RootObject = this };");
        sb.AppendLine("        var errors = new List<ValidationError>();");
        sb.AppendLine();

        foreach (var prop in info.Properties)
        {
            if (prop.CascadeStopOnFirst && prop.Rules.Count > 1)
            {
                sb.AppendLine("        do {");
                foreach (var rule in prop.Rules)
                {
                    EmitRule(sb, prop, rule, "    ", cascade: true);
                }
                sb.AppendLine("        } while (false);");
            }
            else
            {
                foreach (var rule in prop.Rules)
                {
                    EmitRule(sb, prop, rule);
                }
            }
        }

        // Nested IValidatable properties
        if (info.NestedProperties.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Nested validation");
            EmitNestedValidation(sb, info);
        }

        // Cross-field rules from IValidationConfigurator<T>
        if (info.CrossFieldRules.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Cross-field rules");
            EmitCrossFieldRules(sb, info);
        }

        // Conditional rules
        if (info.ConditionalRules.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Conditional rules");
            EmitConditionalRules(sb, info);
        }

        // RuleSet rules
        if (hasRuleSets)
        {
            sb.AppendLine();
            sb.AppendLine("        // RuleSet rules");
            foreach (var rs in info.RuleSetRules)
            {
                sb.AppendLine($"        if (ruleSets == null || ruleSets.Length == 0 || System.Array.IndexOf(ruleSets, \"{EscapeString(rs.Name)}\") >= 0)");
                sb.AppendLine($"        {{");
                foreach (var rule in rs.InnerRules)
                {
                    EmitSingleCrossFieldRule(sb, rule, "            ");
                }
                sb.AppendLine($"        }}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return errors.Count == 0 ? ValidationResult.Success : new ValidationResult(errors);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string __Localize(string property, string defaultMessage)");
        sb.AppendLine("    {");
        sb.AppendLine("        var localizer = ValidationServiceProvider.ServiceProvider?.GetService(typeof(IValidationLocalizer)) as IValidationLocalizer;");
        sb.AppendLine("        return localizer?.GetMessage(property, defaultMessage) ?? defaultMessage;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCodeMap(ValidationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated code map for <c>{info.ClassName}</c> (Validation):");
        sb.AppendLine("/// <list type=\"bullet\">");
        sb.AppendLine($"/// <item><description>Validate() method — compile-time validation from attributes</description></item>");
        sb.AppendLine($"/// <item><description>Implements <see cref=\"IValidatable\"/></description></item>");
        sb.AppendLine("/// </list>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"partial {keyword} {info.ClassName} {{ }}");

        return sb.ToString();
    }

    private static string Err(string prop, string msg)
        => $"new ValidationError(\"{EscapeString(prop)}\", __Localize(\"{EscapeString(prop)}\", \"{EscapeString(msg)}\"))";

    /// <summary>Builds error expression with {PropertyName}/{PropertyValue} placeholder support.</summary>
    private static string ErrWithPlaceholders(string propName, string msg, string accessExpr)
    {
        bool hasPropertyValue = msg.Contains("{PropertyValue}");
        bool hasPropertyName = msg.Contains("{PropertyName}");

        if (!hasPropertyValue && !hasPropertyName)
            return Err(propName, msg);

        // Replace {PropertyName} with the literal property name
        var resolvedMsg = msg.Replace("{PropertyName}", propName);

        if (!hasPropertyValue)
            return Err(propName, resolvedMsg);

        // Contains {PropertyValue} — emit as interpolated string
        var parts = resolvedMsg.Replace("\"", "\\\"").Replace("{PropertyValue}", $"\" + {accessExpr} + \"");
        return $"new ValidationError(\"{EscapeString(propName)}\", __Localize(\"{EscapeString(propName)}\", \"{parts}\"))";
    }

    private static void EmitRule(StringBuilder sb, PropertyValidationInfo prop, ValidationRule rule, string extraIndent = "", bool cascade = false)
    {
        var name = prop.PropertyName;
        var displayName = prop.PropertyName;
        var indent = "        " + extraIndent;
        var brk = cascade ? $" break;" : "";

        switch (rule.Kind)
        {
            case ValidationRuleKind.Required:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is required.";
                var err = ErrWithPlaceholders(name, msg, name);
                if (prop.IsValueType)
                {
                    if (prop.TypeName.EndsWith("?"))
                        sb.AppendLine($"{indent}if ({name} is null) {{ errors.Add({err});{brk} }}");
                }
                else
                {
                    if (cascade)
                    {
                        sb.AppendLine($"{indent}if ({name} is null || {(prop.TypeName == "string" || prop.TypeName == "string?" ? $"string.IsNullOrWhiteSpace({name})" : "false")}) {{ errors.Add({err});{brk} }}");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}if ({name} is null) errors.Add({err});");
                        if (prop.TypeName == "string" || prop.TypeName == "string?")
                            sb.AppendLine($"{indent}else if (string.IsNullOrWhiteSpace({name})) errors.Add({err});");
                    }
                }
                break;
            }

            case ValidationRuleKind.MinLength:
            {
                var len = (int)rule.MinValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at least {len} characters.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && {name}.Length < {len}) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.MaxLength:
            {
                var len = (int)rule.MaxValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at most {len} characters.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && {name}.Length > {len}) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.Range:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be between {rule.MinValue} and {rule.MaxValue}.";
                var err = ErrWithPlaceholders(name, msg, name);
                if (prop.IsNullableRef || prop.TypeName.EndsWith("?"))
                    sb.AppendLine($"{indent}if ({name} is not null && ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue})) {{ errors.Add({err});{brk} }}");
                else
                    sb.AppendLine($"{indent}if ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue}) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.Email:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid email address.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\")) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.Url:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid URL.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && !System.Uri.TryCreate({name}, System.UriKind.Absolute, out _)) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.Match:
            {
                var msg = rule.CustomMessage ?? $"{displayName} does not match the required pattern.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"{rule.Pattern!.Replace("\"", "\"\"")}\")) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.NotEmpty:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must not be empty.";
                var err = ErrWithPlaceholders(name, msg, name);
                if (prop.TypeName == "string" || prop.TypeName == "string?")
                    sb.AppendLine($"{indent}if ({name} is not null && string.IsNullOrWhiteSpace({name})) {{ errors.Add({err});{brk} }}");
                else
                    sb.AppendLine($"{indent}if ({name} is not null && ((System.Collections.ICollection){name}).Count == 0) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.In:
            {
                var values = rule.AllowedValues ?? System.Array.Empty<string>();
                var valuesStr = string.Join(", ", values.Select(v => $"\"{EscapeString(v)}\""));
                var msg = rule.CustomMessage ?? $"{displayName} must be one of: {string.Join(", ", values)}.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && !new[] {{ {valuesStr} }}.Contains({name})) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.NotIn:
            {
                var values = rule.AllowedValues ?? System.Array.Empty<string>();
                var valuesStr = string.Join(", ", values.Select(v => $"\"{EscapeString(v)}\""));
                var msg = rule.CustomMessage ?? $"{displayName} must not be one of: {string.Join(", ", values)}.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && new[] {{ {valuesStr} }}.Contains({name})) {{ errors.Add({err});{brk} }}");
                break;
            }

            case ValidationRuleKind.CreditCard:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is not a valid credit card number.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var __cc = {name}.Replace(\"-\", \"\").Replace(\" \", \"\");");
                sb.AppendLine($"{indent}    var __ccValid = __cc.Length >= 12 && __cc.Length <= 19 && __cc.All(char.IsDigit);");
                sb.AppendLine($"{indent}    if (__ccValid)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var __sum = 0;");
                sb.AppendLine($"{indent}        var __alt = false;");
                sb.AppendLine($"{indent}        for (var __i = __cc.Length - 1; __i >= 0; __i--)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var __n = __cc[__i] - '0';");
                sb.AppendLine($"{indent}            if (__alt)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                __n *= 2;");
                sb.AppendLine($"{indent}                if (__n > 9) __n -= 9;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            __sum += __n;");
                sb.AppendLine($"{indent}            __alt = !__alt;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        __ccValid = __sum % 10 == 0;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    if (!__ccValid) {{ errors.Add({err});{brk} }}");
                sb.AppendLine($"{indent}}}");
                break;
            }

            case ValidationRuleKind.Iban:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is not a valid IBAN.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var __iban = {name}.Replace(\" \", \"\").ToUpperInvariant();");
                sb.AppendLine($"{indent}    var __ibanValid = __iban.Length >= 15 && __iban.Length <= 34");
                sb.AppendLine($"{indent}        && __iban[0] >= 'A' && __iban[0] <= 'Z' && __iban[1] >= 'A' && __iban[1] <= 'Z'");
                sb.AppendLine($"{indent}        && __iban[2] >= '0' && __iban[2] <= '9' && __iban[3] >= '0' && __iban[3] <= '9'");
                sb.AppendLine($"{indent}        && __iban.All(__c => (__c >= 'A' && __c <= 'Z') || (__c >= '0' && __c <= '9'));");
                sb.AppendLine($"{indent}    if (__ibanValid)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var __remainder = 0;");
                sb.AppendLine($"{indent}        var __rearranged = __iban.Substring(4) + __iban.Substring(0, 4);");
                sb.AppendLine($"{indent}        foreach (var __ch in __rearranged)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (char.IsDigit(__ch)) __remainder = (__remainder * 10 + (__ch - '0')) % 97;");
                sb.AppendLine($"{indent}            else");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                var __value = __ch - 'A' + 10;");
                sb.AppendLine($"{indent}                __remainder = (__remainder * 100 + __value) % 97;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        __ibanValid = __remainder == 1;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    if (!__ibanValid) {{ errors.Add({err});{brk} }}");
                sb.AppendLine($"{indent}}}");
                break;
            }

            case ValidationRuleKind.Phone:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is not a valid phone number.";
                var err = ErrWithPlaceholders(name, msg, name);
                sb.AppendLine($"{indent}if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"^\\+?[\\d\\s\\-\\(\\)]{{7,20}}$\")) {{ errors.Add({err});{brk} }}");
                break;
            }
        }
    }

    private static int _blockRuleCounter;

    private static void EmitCrossFieldRules(StringBuilder sb, ValidationInfo info)
    {
        foreach (var rule in info.CrossFieldRules)
        {
            EmitSingleCrossFieldRule(sb, rule, "        ");
        }
    }

    private static void EmitSingleCrossFieldRule(StringBuilder sb, CrossFieldRule rule, string indent)
    {
        var prop = rule.LeftProperty ?? "";
        switch (rule.Kind)
        {
            case CrossFieldRuleKind.Expression:
                if (rule.IsBlockBody)
                {
                    var fnName = $"__BlockRule_{_blockRuleCounter++}";
                    sb.AppendLine($"{indent}bool {fnName}()");
                    sb.AppendLine($"{indent}{rule.ExpressionText}");
                    sb.AppendLine($"{indent}if (!{fnName}()) errors.Add({Err(prop, rule.Message)});");
                }
                else
                {
                    sb.AppendLine($"{indent}if (!({rule.ExpressionText})) errors.Add({Err(prop, rule.Message)});");
                }
                break;
            case CrossFieldRuleKind.GreaterThan:
                sb.AppendLine($"{indent}if (!({rule.LeftProperty} > {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
            case CrossFieldRuleKind.GreaterThanOrEqual:
                sb.AppendLine($"{indent}if (!({rule.LeftProperty} >= {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
            case CrossFieldRuleKind.LessThan:
                sb.AppendLine($"{indent}if (!({rule.LeftProperty} < {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
            case CrossFieldRuleKind.LessThanOrEqual:
                sb.AppendLine($"{indent}if (!({rule.LeftProperty} <= {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
            case CrossFieldRuleKind.EqualTo:
                sb.AppendLine($"{indent}if (!object.Equals({rule.LeftProperty}, {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
            case CrossFieldRuleKind.NotEqualTo:
                sb.AppendLine($"{indent}if (object.Equals({rule.LeftProperty}, {rule.RightProperty})) errors.Add({Err(prop, rule.Message)});");
                break;
        }
    }

    private static void EmitConditionalRules(StringBuilder sb, ValidationInfo info)
    {
        foreach (var cond in info.ConditionalRules)
        {
            sb.AppendLine($"        if ({cond.ConditionExpression})");
            sb.AppendLine($"        {{");
            foreach (var rule in cond.InnerRules)
            {
                EmitSingleCrossFieldRule(sb, rule, "            ");
            }
            sb.AppendLine($"        }}");
        }
    }

    private static void EmitNestedValidation(StringBuilder sb, ValidationInfo info)
    {
        for (int i = 0; i < info.NestedProperties.Count; i++)
        {
            var nested = info.NestedProperties[i];
            if (nested.IsCollection)
            {
                if (nested.IsNullable)
                    sb.AppendLine($"        if ({nested.PropertyName} is not null)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var __idx{i} = 0;");
                sb.AppendLine($"            foreach (var __item{i} in {nested.PropertyName})");
                sb.AppendLine($"            {{");
                sb.AppendLine($"                if (__item{i} is IValidatable __v{i})");
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    var __nested{i} = __v{i}.Validate(context.ForNested(this, \"{nested.PropertyName}[\" + __idx{i} + \"]\"));");
                sb.AppendLine($"                    if (!__nested{i}.IsValid)");
                sb.AppendLine($"                        foreach (var __e in __nested{i}.ValidationErrors) errors.Add(new ValidationError(\"{nested.PropertyName}[\" + __idx{i} + \"].\" + __e.Property, __e.Message));");
                sb.AppendLine($"                }}");
                sb.AppendLine($"                __idx{i}++;");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        if ({nested.PropertyName} is IValidatable __v{i})");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var __nested{i} = __v{i}.Validate(context.ForNested(this, \"{nested.PropertyName}\"));");
                sb.AppendLine($"            if (!__nested{i}.IsValid)");
                sb.AppendLine($"                foreach (var __e in __nested{i}.ValidationErrors) errors.Add(new ValidationError(\"{nested.PropertyName}.\" + __e.Property, __e.Message));");
                sb.AppendLine($"        }}");
            }
        }
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
